### ISSUE TITLE
Add CRAN installation instructions

### ISSUE THREAD

**Issue by jrosen48** [cddesja/profileR#27]
This pertains to [JOSS review 1941](https://github.com/openjournals/joss-reviews/issues/1941).

Because the README includes code to install the developmental version on GitHub, readers may not think that a version is available through CRAN (though I note that the README does mention this). What do you think of including `install.packages('profileR')` to the README?

Relatedly, what do you think of including installation instructions in the paper?

**Comment by cddesja** [comment]
I think both of these are good ideas. I'll update the README.md file for that and make sure that the installations instruction get added to the paper.

**Comment by jrosen48** [comment]
Great! Thanks. When done, I think this review element will be addressed.

**Comment by okanbulut** [comment]
We have the installation instructions in README.md. We will add a similar information in the paper as well @cddesja

**Comment by cddesja** [comment]
This has been added to paper.md.
