### ISSUE TITLE
Include tests

### ISSUE THREAD

**Issue by jrosen48** [cddesja/profileR#29]
This pertains to [JOSS review 1941](https://github.com/openjournals/joss-reviews/issues/1941).

The review criteria require that the following be addressed; I do not yet see these in the repository or documentation:

`Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?`

**Comment by cddesja** [comment]
@okanbulut and I will need to think about this. We don't have any tests add. We can look at the testthat package. @jrosen48, is this something that should have been added before the article was submitted?

**Comment by jrosen48** [comment]
Yes, I think so. It is clearly in the review criteria, and all review criteria must be met before acceptance.

**Comment by jrosen48** [comment]
But, I think it is okay that it isn't, as long as you address this now (IMHO).

**Comment by cddesja** [comment]
I think I need some clarity on what "**Automated tests**: Are there automated tests or manual steps described so that the functionality of the software can be verified?" means exactly. We'd prefer to not use the testthat package to create tests, primarily because Wickham package's are a [moving target](https://www.quora.com/Do-you-expect-the-tidyverse-to-be-the-part-of-core-R-packages-some-day) and functions are often deprecated and packages get orphaned.

From a user's perspective, if 

1. The package installs without error and
2. The examples run and can be compared, for example against a wiki.

I would say the functionality of the software can be verified.

**Comment by jrosen48** [comment]
I don't agree with your description of Wickham's packages, but, I take your point. 

You can include tests without using Wickham's packages, so I think this comes down to your argument about the manual steps that can verify the functionality. 

I'd suggest tests, but could be convinced that the steps you described - if elaborated and formalized a little, maybe - are satisfactory for this review criterion.

**Comment by cddesja** [comment]
@jrosen48, what are your thoughts about [this](https://github.com/cddesja/profileR/wiki/Verifying-the-installation-of-profileR)? We can link to it on the README.md file and I can add a note in the paper.md if you think it works. If that isn't satisfactory, please let us know.

Also, I'm not trying to denigrate Wickham's work or the greater work of the collection of packages in the tidyverse. Their stuff is amazing and Wickham is incredibly prolific. I have just had my own experiences revisiting analyses from the past that have made me want to stay as close to base R as possible.

**Comment by jrosen48** [comment]
I am satisfied with this. Idea to take or leave. What if this were in a vignette? That way, it would have to get built (i.e., upon installation and CRAN submission, in two key cases). That way, if there were ever an error introduced in one of the functions used in one of the 24 examples, you would know that way.

**Comment by cddesja** [comment]
@jrosen48, I think that's a good idea. I'll add it as a vignette.

**Comment by cddesja** [comment]
@jrosen48, added. Thanks for the suggestion.

**Comment by jrosen48** [comment]
Cool. Thanks for such a constructive review experience. I've signed off on my review in the review repo!
