### ISSUE TITLE
Include community guidelines

### ISSUE THREAD

**Issue by jrosen48** [cddesja/profileR#30]
This pertains to [JOSS review 1941](https://github.com/openjournals/joss-reviews/issues/1941).

The review criteria require that the following be addressed; I do not yet see these in the repository or documentation:

`Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support`

**Comment by cddesja** [comment]
@okanbulut and I will add a note to the article regarding all 3.

**Comment by jrosen48** [comment]
What would you think of adding this to the repository - perhaps to the README - instead of to the article? I think the article is more for general info, whereas the repository is for folks who may wish to do these things (contribute, report issues, find help/support).

**Comment by wjakethompson** [comment]
I agree that the repository is probably a better place for this to live. An alternative to the README would be to add a CODE_OF_CONDUCT.md and CONTRIBUTING.md file. You probably don't need anything this extensive, but the [ggplot2 repository](https://github.com/tidyverse/ggplot2) has really good examples of both.

**Comment by okanbulut** [comment]
We have now included all of the requested information in the README document. We also included a Code of Conduct document. Thanks for the great suggestions!
