### ISSUE TITLE
Include a review of the state of the field

### ISSUE THREAD

**Issue by jrosen48** [cddesja/profileR#31]
This pertains to [JOSS review 1941](https://github.com/openjournals/joss-reviews/issues/1941).

The review criteria require that the following be addressed; I do not yet see these in the repository or documentation:

`State of the field: Do the authors describe how this software compares to other commonly-used packages?`

This is selfish, but could a statement of how this package differs from another on profile analysis associated with JOSS ([tidyLPA](https://joss.theoj.org/papers/10.21105/joss.00978)). To be sure, I can see that this package includes functionality above and beyond what tidyLPA offers, and I think there is room for more than one package for carrying out profile analysis where it comes to JOSS and R (of course), but think that a distinction between the two may be useful to readers.

**Comment by cddesja** [comment]
@jrosen48, sure. We can add a couple of sentences to the manuscript that compare our package with yours and our unpublished vignette has a greater comparison of these approaches. 

@jrosen48, do you happen to know if we're suppose to fix the manuscript based on these issues, close the issue, and then inform you and the editor?

**Comment by jrosen48** [comment]
I think that process that you described is exactly right! In my experience (as an author and reviewer), there are usually at least a few changes to the paper needed, and when there are changes to the paper, you can have it re-rendered.

**Comment by cddesja** [comment]
Added a reference to tidyLPA, mclust, and Mplus and made a distinction of our package from these methods.
